package civilviolence;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author maleco
 */
public class GUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     *
     * @param grid
     * @param param
     */
    public GUIFrame(Cell[][] grid, final HashMap<String, Integer> param) {
        initComponents();

        // Set the layouts
        GridPanel.setLayout(
                new GridLayout(
                        param.get("LENGTH"),
                        param.get("WIDTH")
                ));
        ControlFrame.setLayout(new GridLayout(1, 3));

        // Maximize the screen
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        // Set the panel split
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        jSplitPane1.setDividerLocation(screenSize.height);
        jSplitPane1.setEnabled(false);

        // Add the grid buttons
        setGridButtons(grid, param);

    }

    private void setGridButtons(final Cell[][] grid, HashMap<String, Integer> param) {
        // Add the grid buttons
        for (int row = 0; row < param.get("LENGTH"); ++row) {
            for (int col = 0; col < param.get("WIDTH"); ++col) {

                // Create the button
                final JButton btn = new javax.swing.JButton();
                final int finalRow = row;
                final int finalCol = col;

                btn.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent event) {

                        final int nrNeutral = grid[finalRow][finalCol].getNrNeutral();
                        final int nrHostiles = grid[finalRow][finalCol].getNrHostiles();
                        final int nrCops = grid[finalRow][finalCol].getNrGood();
                        final int totalNeutrals = grid[finalRow][finalCol].getNrNeutral();
                        final int totalHostiles = grid[finalRow][finalCol].getNrHostiles();

                        // Set the background
                        if (nrHostiles == 0) {
                            btn.setBackground(new Color(0, 0, 255));
                        } else if (nrCops == 0 & nrHostiles != 0) {
                            btn.setBackground(new Color(255, 0, 0));
                        } else {
                            // Range from -1 to 1
                            float temp = ((((float) (nrCops - nrHostiles) / (nrCops + nrHostiles)) + 1) / 2) * 255;
                            btn.setBackground(new Color(
                                    (int) (255 - temp),
                                    0,
                                    (int) temp
                            ));
                        }
                        // Set the text as number of neutrals
                        btn.setFont(new Font("Arial", Font.PLAIN, 12));
                        btn.setMargin(new Insets(0, 0, 0, 0));
                        btn.setForeground(Color.WHITE);
                        btn.setText("" + grid[finalRow][finalCol].getNrNeutral());

                        // Adjust the information box on buttonclick
                        // btn.addActionListener((ActionEvent e) -> {
                        infoField.setText(
                                "\n\n\t Number of neutrals on this site:\t" + nrNeutral + '\n'
                                + "\t Number of hostiles on this site:\t" + nrHostiles + '\n'
                                + "\t Number of cops on this site:\t\t" + nrCops
                                + "\n\n"
                                + "\t Total of neutral on this site:\t" + totalNeutrals + '\n'
                                + "\t Total of hostiles on this site:\t" + totalHostiles
                        );
                    }
                });

                // Add the button to the group and the panel
                buttonGroup1.add(btn);
                GridPanel.add(btn);
            }
        }
    }

    public void updateGUI() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        GridPanel = new javax.swing.JPanel();
        RightPanel = new javax.swing.JPanel();
        infoField = new javax.swing.JTextPane();
        ControlFrame = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setDividerSize(25);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(600, 400));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(600, 400));

        GridPanel.setMinimumSize(new java.awt.Dimension(400, 400));
        GridPanel.setPreferredSize(new java.awt.Dimension(400, 400));
        GridPanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout GridPanelLayout = new javax.swing.GroupLayout(GridPanel);
        GridPanel.setLayout(GridPanelLayout);
        GridPanelLayout.setHorizontalGroup(
            GridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        GridPanelLayout.setVerticalGroup(
            GridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(GridPanel);

        RightPanel.setLayout(new java.awt.GridLayout(0, 1));

        infoField.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        RightPanel.add(infoField);

        javax.swing.GroupLayout ControlFrameLayout = new javax.swing.GroupLayout(ControlFrame);
        ControlFrame.setLayout(ControlFrameLayout);
        ControlFrameLayout.setHorizontalGroup(
            ControlFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        ControlFrameLayout.setVerticalGroup(
            ControlFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        RightPanel.add(ControlFrame);

        jSplitPane1.setRightComponent(RightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel ControlFrame;
    public javax.swing.JPanel GridPanel;
    public javax.swing.JPanel RightPanel;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JTextPane infoField;
    public javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
